import { Song } from '@/types'

export const songs90s: Song[] = [
  // ── 既存3曲（PDF反映済） ──
  {
    id: 'song_004',
    title: 'チェリー',
    artist: 'スピッツ',
    year: 1996,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'Eze6-eHmtJg',
    sections: [
      { label: 'イントロ', chords: ['C', 'G', 'Am', 'F'] },
      { label: 'Aメロ', chords: ['C', 'G', 'Am', 'Em', 'F', 'C', 'F', 'G', 'C', 'G', 'Am', 'Em', 'F', 'G', 'C', 'Am', 'F', 'G', 'Cadd9'] },
      { label: 'サビ', chords: ['G', 'Am', 'Em', 'F', 'C', 'Am', 'Em', 'F', 'C', 'Am', 'Em', 'F', 'G', 'C'] },
      { label: '間奏', chords: ['Bbadd9', 'Am', 'F', 'Am', 'F', 'Am', 'G', 'F', 'Fmaj7'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '初心者向け'],
  },
  {
    id: 'song_005',
    title: 'Tomorrow never knows',
    artist: 'Mr.Children',
    year: 1994,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'Nxwt_s1lM04',
    sections: [
      { label: 'イントロ', chords: ['Fmaj7', 'G/F', 'Em7', 'Fmaj7'] },
      { label: 'Aメロ', chords: ['Fmaj7', 'G/F', 'Em7', 'Fmaj7', 'G/F', 'Am9'] },
      { label: 'Bメロ', chords: ['Em7', 'Am7', 'Dm9', 'Cadd9', 'Fmaj7', 'C', 'G'] },
      { label: 'サビ', chords: ['D', 'G', 'A', 'E7', 'Bm', 'G', 'A', 'E7', 'D', 'G', 'A', 'E7', 'Bm', 'E'] },
      { label: '間奏', chords: ['Fmaj7', 'G/F', 'Em7', 'Fmaj7'] },
      { label: 'アウトロ', chords: ['Em7', 'D', 'C', 'A', 'G'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['定番', '弾き語り', 'テンション多め'],
  },
  {
    id: 'song_006',
    title: 'HOWEVER',
    artist: 'GLAY',
    year: 1997,
    decade: '90s',
    genre: 'rock',
    youtubeId: 'gPcPseeICjs',
    sections: [
      { label: 'イントロ', chords: ['G', 'D/F#', 'Em7', 'G/D', 'C', 'D', 'Gsus4', 'G', 'G', 'D/F#', 'Em', 'G/D', 'C', 'D', 'G'] },
      { label: '間奏', chords: ['Em7', 'D', 'G', 'Em7', 'D', 'G', 'Cmaj7', 'D', 'G'] },
      { label: 'Aメロ', chords: ['C', 'Em', 'C', 'Em', 'C', 'Em', 'C', 'Em', 'D', 'B'] },
      { label: 'Bメロ', chords: ['G', 'D/F#', 'Em', 'Em/D', 'C', 'D', 'Gsus4', 'G', 'G', 'D/F#', 'Em', 'Em/D', 'C', 'D', 'G', 'Em', 'D', 'G', 'Em', 'D', 'G', 'Cmaj7', 'D', 'G'] },
      { label: 'サビ', chords: ['G', 'D/F#', 'Em', 'Em/D', 'C', 'D', 'Gsus4', 'G', 'G', 'D/F#', 'Em', 'Em/D', 'C', 'D', 'G', 'Em', 'D', 'G', 'Em', 'D', 'G', 'C', 'D', 'B/D#', 'Em'] },
      { label: 'アウトロ', chords: ['C', 'D', 'Em', 'EmM7/F#', 'Em7', 'A7', 'C', 'D', 'G'] },
    ],
    capo: 5,
    difficulty: 'medium',
    tags: ['バラード', '定番', '弾き語り'],
  },
  // ── 以下、PDF反映（2回目バッチ） ──
  {
    id: 'song_037',
    title: 'ロビンソン',
    artist: 'スピッツ',
    year: 1995,
    decade: '90s',
    genre: 'jpop',
    youtubeId: '51CH3dPaWXc',
    sections: [
      { label: 'イントロ', chords: ['Dm7', 'C#m7', 'F#sus4', 'F#m'] },
      { label: 'Aメロ', chords: ['Dm7', 'C#m7', 'F#sus4', 'F#m'] },
      { label: 'Bメロ', chords: ['A', 'Bm7', 'E', 'F#m'] },
      { label: 'サビ', chords: ['D', 'A', 'Bm7', 'E', 'F#m', 'Dm7', 'C#m7', 'F#sus4', 'F#'] },
      { label: '間奏', chords: ['Dm7', 'C#m7', 'F#sus4', 'F#m'] },
      { label: 'アウトロ', chords: ['A', 'Bm7', 'E', 'F#m'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_038',
    title: '空も飛べるはず',
    artist: 'スピッツ',
    year: 1994,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'h-kQw4JqCHE',
    sections: [
      { label: 'イントロ', chords: ['C', 'G', 'Am'] },
      { label: 'Aメロ', chords: ['C', 'G', 'Am', 'F', 'C', 'D7', 'G'] },
      { label: 'Bメロ', chords: ['Am', 'Fm7', 'G7', 'C'] },
      { label: 'サビ', chords: ['C', 'G', 'Am', 'F', 'G', 'Em7', 'Am', 'F', 'G7'] },
      { label: '間奏', chords: ['Dm7', 'Em7', 'Fm7', 'G7'] },
      { label: 'アウトロ', chords: ['C', 'G', 'Am'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_039',
    title: '名もなき詩',
    artist: 'Mr.Children',
    year: 1996,
    decade: '90s',
    genre: 'jpop',
    youtubeId: '4gd2oVFUcz0',
    sections: [
      { label: 'イントロ', chords: ['G'] },
      { label: 'Aメロ', chords: ['G', 'Am7', 'G', 'Am7'] },
      { label: 'Bメロ', chords: ['C', 'D', 'B7', 'Em', 'Em7'] },
      { label: 'サビ', chords: ['Am7', 'Bm7', 'C', 'B7sus4', 'B7', 'Em'] },
      { label: '間奏', chords: ['A7', 'C', 'D', 'G'] },
      { label: 'アウトロ', chords: ['G', 'Em', 'C', 'D'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_040',
    title: 'CROSS ROAD',
    artist: 'Mr.Children',
    year: 1993,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'ESsijJ2AUGQ',
    sections: [
      { label: 'イントロ', chords: ['Gm7', 'A/G', 'F#m7', 'B7sus4', 'B'] },
      { label: 'Aメロ', chords: ['Em7', 'F#m7', 'G', 'A'] },
      { label: 'Bメロ', chords: ['D', 'Em7', 'F#m7', 'Bm7', 'Em7'] },
      { label: 'サビ', chords: ['Gm7', 'A/G', 'F#m7', 'B7sus4', 'Em7', 'G', 'A', 'Cadd9'] },
      { label: '間奏', chords: ['D', 'Em7', 'F#m7', 'Bm7'] },
      { label: 'アウトロ', chords: ['Gm7', 'A/G', 'F#m7', 'B7sus4'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_041',
    title: '負けないで',
    artist: 'ZARD',
    year: 1993,
    decade: '90s',
    genre: 'jpop',
    youtubeId: '_4DJkOUU648',
    sections: [
      { label: 'イントロ', chords: ['Eb', 'Am', 'D', 'G', 'D', 'Em', 'Bm', 'C', 'G', 'Am', 'D'] },
      { label: 'Aメロ', chords: ['C', 'D', 'D/C', 'Bm', 'Em', 'C', 'D/C', 'Bm', 'E7', 'Am', 'AmM7', 'Am7', 'D', 'Em', 'B7', 'G', 'A7', 'C', 'D'] },
      { label: 'サビ', chords: ['G', 'D', 'Em', 'Bm7', 'C', 'G', 'Am7', 'D7', 'G', 'D', 'Em', 'Bm7', 'C', 'G', 'Am7', 'B7', 'C', 'D', 'Am7', 'C', 'D'] },
      { label: 'アウトロ', chords: ['Eb', 'Am', 'D', 'Am', 'AmM7', 'Am7', 'D', 'Em', 'B', 'G', 'A', 'C', 'D'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', '応援歌'],
  },
  {
    id: 'song_042',
    title: '揺れる想い',
    artist: 'ZARD',
    year: 1993,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'jaFE9YH3Zmk',
    sections: [
      { label: 'イントロ', chords: ['Fm', 'F'] },
      { label: 'Aメロ', chords: ['Bb', 'D', 'Eb', 'Bb', 'F/A', 'Gm', 'C', 'Fsus4', 'F'] },
      { label: 'Bメロ', chords: ['Bb', 'F/A', 'Gm', 'Dm/F'] },
      { label: 'サビ', chords: ['Bb', 'D', 'Eb', 'Bb', 'F/A', 'Gm', 'C', 'Fsus4', 'F', 'Bb'] },
      { label: '間奏', chords: ['F/A', 'Gm', 'C', 'Fsus4', 'F', 'Bb'] },
      { label: 'アウトロ', chords: ['F/A', 'Gm', 'C', 'Fsus4', 'F'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['定番', '弾き語り', '夏'],
  },
  {
    id: 'song_043',
    title: 'ラブ・ストーリーは突然に',
    artist: '小田和正',
    year: 1991,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'VwJruL9nBwQ',
    sections: [
      { label: 'イントロ', chords: ['Em', 'A', 'Bm', 'F#m', 'G', 'D', 'C#m', 'F#'] },
      { label: 'Aメロ', chords: ['Em', 'A', 'Bm', 'F#m', 'G', 'D', 'Em', 'A', 'Bm', 'A'] },
      { label: 'Bメロ', chords: ['Gm7', 'Fm7'] },
      { label: 'サビ', chords: ['Em', 'A', 'Bm', 'F#m', 'G', 'D', 'C#m', 'F#'] },
      { label: 'ブリッジ', chords: ['Gm7', 'D', 'C#m7', 'F#7'] },
      { label: 'アウトロ', chords: ['Em', 'G/A', 'Bm7', 'F#m'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_044',
    title: 'どんなときも。',
    artist: '槇原敬之',
    year: 1991,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'b88pxLpMZKk',
    sections: [
      { label: 'イントロ', chords: ['D', 'Dsus4', 'A7', 'Bm', 'Gm', 'Em', 'D', 'A'] },
      { label: 'Aメロ', chords: ['D', 'Dsus4', 'A7', 'Bm', 'Gm', 'Em', 'D', 'A', 'Asus4'] },
      { label: 'Bメロ', chords: ['D', 'Gm7', 'Bm7'] },
      { label: 'サビ', chords: ['G', 'D', 'Em7', 'A7sus4', 'A7'] },
      { label: 'ブリッジ', chords: ['Gm7', 'Bm7', 'Gm7', 'Bm7'] },
      { label: 'アウトロ', chords: ['D', 'Dsus4', 'A7', 'Bm', 'Gm', 'Em', 'D', 'A'] },
    ],
    capo: 4,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', '応援歌'],
  },
  {
    id: 'song_045',
    title: 'もう恋なんてしない',
    artist: '槇原敬之',
    year: 1992,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'naz0-szzYXk',
    sections: [
      { label: 'イントロ', chords: ['C', 'Dm7', 'Em', 'E7', 'Am7'] },
      { label: 'Aメロ', chords: ['C', 'Dm7', 'Em', 'E7', 'Am7', 'Dm7', 'G', 'Csus4', 'C'] },
      { label: 'Bメロ', chords: ['Am7', 'Em7'] },
      { label: 'サビ', chords: ['C', 'Dm7', 'Em', 'E7', 'Am7'] },
      { label: 'ブリッジ', chords: ['Fmaj7', 'E7', 'Am7'] },
      { label: 'アウトロ', chords: ['C', 'Dm7', 'Em', 'E7', 'Am7'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_046',
    title: '遠く遠く',
    artist: '槇原敬之',
    year: 1992,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'XIQHcECoDgk',
    sections: [
      { label: 'イントロ', chords: ['C', 'G7/B', 'Am7', 'Am7/G'] },
      { label: 'Aメロ', chords: ['C', 'G7/B', 'Am7', 'Am7/G', 'Fmaj7', 'E7', 'Am7', 'G7'] },
      { label: 'Bメロ', chords: ['Dm7', 'G7', 'C', 'C7'] },
      { label: 'サビ', chords: ['Fmaj7', 'E7', 'Am7', 'Dm7/G'] },
      { label: 'ブリッジ', chords: ['Dm7', 'Dm7/G', 'Csus4', 'C'] },
      { label: 'アウトロ', chords: ['C', 'G7/B', 'Am7', 'Am7/G'] },
    ],
    capo: 1,
    difficulty: 'hard',
    tags: ['定番', '弾き語り', '春'],
  },
  {
    id: 'song_047',
    title: 'Hello, Again 〜昔からある場所〜',
    artist: 'My Little Lover',
    year: 1995,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'RkF5_BpBQU4',
    sections: [
      { label: 'イントロ', chords: ['D', 'G', 'A', 'Bm', 'A'] },
      { label: 'Aメロ', chords: ['D', 'G', 'A', 'Bm', 'A', 'D', 'G', 'F#m7', 'Bm7'] },
      { label: 'Bメロ', chords: ['G', 'A', 'Bm7'] },
      { label: 'サビ', chords: ['D', 'G', 'A', 'Bm', 'A', 'D', 'G', 'F#m7', 'Bm7'] },
      { label: '間奏', chords: ['D', 'G', 'A', 'Bm', 'A'] },
      { label: 'アウトロ', chords: ['D', 'G', 'A', 'Bm', 'A'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', '90s'],
  },
  {
    id: 'song_048',
    title: 'Tomorrow',
    artist: '岡本真夜',
    year: 1995,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'IxN5s8YipbI',
    sections: [
      { label: 'イントロ', chords: ['C#sus4', 'C', 'F', 'C', 'Dm', 'Am'] },
      { label: 'Aメロ', chords: ['F', 'C', 'Dm', 'Am', 'Bb', 'F', 'Gm7', 'F'] },
      { label: 'Bメロ', chords: ['F', 'C', 'Dm', 'Am', 'Bb', 'F', 'Gm7', 'C7', 'F'] },
      { label: 'サビ', chords: ['Bb', 'F', 'Gm7', 'C', 'Ddim'] },
      { label: '間奏', chords: ['F', 'C', 'Dm', 'Am'] },
      { label: 'アウトロ', chords: ['F', 'C', 'Dm', 'Am'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['定番', '弾き語り', '応援歌'],
  },
  {
    id: 'song_049',
    title: 'One more time, One more chance',
    artist: '山崎まさよし',
    year: 1997,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'BqFftJDXii0',
    sections: [
      { label: 'イントロ', chords: ['A', 'A#m7', 'D', 'Dm'] },
      { label: 'Aメロ', chords: ['A', 'A#m7', 'D', 'Dm', 'C#m', 'F#m', 'Bm', 'F'] },
      { label: 'Bメロ', chords: ['A', 'A#m7', 'D', 'Dm'] },
      { label: 'サビ', chords: ['C#m', 'F#m', 'Bm', 'F', 'A', 'Am7', 'G', 'F#'] },
      { label: '間奏', chords: ['Bm7', 'E'] },
      { label: 'ブリッジ', chords: ['G', 'G', 'G', 'G'] },
      { label: 'アウトロ', chords: ['A', 'Am7', 'G', 'F#'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['バラード', '定番', '弾き語り'],
  },
  {
    id: 'song_050',
    title: '少年時代',
    artist: '井上陽水',
    year: 1990,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dNS4rE2dKJA',
    sections: [
      { label: 'イントロ', chords: ['D', 'A', 'Bm7', 'A', 'D', 'A', 'Bm7', 'E7', 'A'] },
      { label: 'Aメロ', chords: ['D', 'A', 'Bm7', 'E7', 'A', 'E', 'C#7', 'F#m'] },
      { label: 'Bメロ', chords: ['D', 'A', 'Bm7', 'E7', 'A', 'Bm7', 'E7', 'A'] },
      { label: 'サビ', chords: ['A', 'E', 'C#7', 'F#m', 'D', 'A', 'Bm7', 'E7', 'A'] },
      { label: 'ブリッジ', chords: ['C#m7-5', 'D', 'Dm', 'A'] },
      { label: 'アウトロ', chords: ['D', 'A', 'Bm7', 'E7', 'A'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['定番', '弾き語り', '青春'],
  },
  {
    id: 'song_051',
    title: 'SAY YES',
    artist: 'CHAGE and ASKA',
    year: 1991,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'Q9qAyt0G-jM',
    sections: [
      { label: 'イントロ', chords: ['D', 'Em7', 'D', 'Em7'] },
      { label: 'Aメロ', chords: ['D', 'Em7', 'F#m', 'G', 'Em7', 'Bm', 'Em', 'A'] },
      { label: 'Bメロ', chords: ['G/A', 'A', 'D', 'Em7', 'F#m', 'C#7', 'F#m7', 'Bm7', 'E7'] },
      { label: 'サビ', chords: ['A', 'Gmaj7', 'C#7', 'C#m7'] },
      { label: '間奏', chords: ['D', 'Em7', 'D', 'Em7'] },
      { label: 'ブリッジ', chords: ['A', 'Em7', 'A'] },
      { label: 'アウトロ', chords: ['D', 'Em7', 'D', 'Em7'] },
    ],
    capo: 1,
    difficulty: 'hard',
    tags: ['定番', '弾き語り', 'デュエット'],
  },
  {
    id: 'song_052',
    title: '君がいるだけで',
    artist: '米米CLUB',
    year: 1992,
    decade: '90s',
    genre: 'jpop',
    youtubeId: '5Q8vU0GWGzM',
    sections: [
      { label: 'イントロ', chords: ['Dm7', 'Dm7/G'] },
      { label: 'Aメロ', chords: ['Cmaj7', 'Am7', 'Dm7', 'Dm7/G'] },
      { label: 'Bメロ', chords: ['Em7', 'Em7/A', 'Dm7/G'] },
      { label: 'サビ', chords: ['Cmaj7', 'Am7', 'Dm7', 'Dm7/G', 'Cmaj7', 'Am7'] },
      { label: '間奏', chords: ['Dm7', 'Dm7/G', 'Cmaj7', 'Am7'] },
      { label: 'アウトロ', chords: ['Dm7', 'Dm7/G'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', 'バラード'],
  },
  {
    id: 'song_053',
    title: 'らいおんハート',
    artist: 'SMAP',
    year: 1999,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'MdRCoN-4ZBE',
    sections: [
      { label: 'イントロ', chords: ['G', 'Fm7', 'Em7', 'Em7/A'] },
      { label: 'Aメロ', chords: ['G', 'Fm7', 'Em7', 'Em7/A', 'D'] },
      { label: 'Bメロ', chords: ['Am7/D', 'D', 'Dm7/G', 'Gm7', 'Fm7', 'B7'] },
      { label: 'サビ', chords: ['Em7', 'Em7/A', 'Dm7/G', 'Am7', 'Fm7', 'Dm7/G'] },
      { label: 'アウトロ', chords: ['G', 'Fm7', 'Em7', 'Em7/A'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['定番', '弾き語り', 'バラード'],
  },
  {
    id: 'song_054',
    title: 'セロリ',
    artist: 'SMAP',
    year: 1998,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'zCW9Ls4PbJQ',
    sections: [
      { label: 'イントロ', chords: ['Dm7', 'Bm7', 'Em', 'A'] },
      { label: 'Aメロ', chords: ['Dm7', 'Bm7', 'Em', 'A'] },
      { label: 'Bメロ', chords: ['Em', 'Dm7', 'Gm7', 'Gm7', 'Fm7', 'B7'] },
      { label: 'サビ', chords: ['Gm7', 'Em7', 'Em7/A', 'Dm7'] },
      { label: 'アウトロ', chords: ['Dm7', 'Bm7', 'Em', 'A'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', '90s'],
  },
  {
    id: 'song_055',
    title: 'DEPARTURES',
    artist: 'globe',
    year: 1996,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'FBi9J_a-i0c',
    sections: [
      { label: 'イントロ', chords: ['Em', 'Bm7/E', 'Cmaj7', 'Bm7/E'] },
      { label: 'Aメロ', chords: ['Em', 'Bm7/E', 'Cmaj7', 'Bm7/E', 'Em'] },
      { label: 'Bメロ', chords: ['G6', 'Cmaj7', 'D6', 'Em7'] },
      { label: 'サビ', chords: ['Cmaj7', 'D', 'Gmaj7', 'Cmaj7', 'D', 'Gmaj7'] },
      { label: 'アウトロ', chords: ['Bm7/E', 'Cmaj7', 'Bm7/E', 'Em'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['定番', '90s'],
  },
  {
    id: 'song_056',
    title: 'ズルい女',
    artist: 'シャ乱Q',
    year: 1994,
    decade: '90s',
    genre: 'rock',
    youtubeId: 'bplLbHAGSAM',
    sections: [
      { label: 'イントロ', chords: ['Am'] },
      { label: 'Aメロ', chords: ['Am', 'Em7', 'Em7sus4', 'E7', 'Am'] },
      { label: 'Bメロ', chords: ['C', 'G', 'F', 'Am', 'G/C', 'C'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'G', 'F', 'G', 'Am'] },
      { label: 'アウトロ', chords: ['F', 'Em7', 'Em7sus4', 'E7', 'Am'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '90s'],
  },
  {
    id: 'song_057',
    title: '空と君のあいだに',
    artist: '中島みゆき',
    year: 1994,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'U2jEWTrExsg',
    sections: [
      { label: 'イントロ', chords: ['D', 'E', 'F#m'] },
      { label: 'Aメロ', chords: ['A', 'D/A', 'A', 'E/G#', 'F#m', 'Cm7', 'D', 'A/C#'] },
      { label: 'Bメロ', chords: ['D', 'E', 'F#m'] },
      { label: 'サビ', chords: ['F#m', 'Cm7', 'Bm7', 'Cm7', 'F#m'] },
      { label: 'アウトロ', chords: ['Bm', 'Cm', 'F#m', 'A', 'E'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_058',
    title: '糸',
    artist: '中島みゆき',
    year: 1992,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'jOegTv3a2h4',
    sections: [
      { label: 'イントロ', chords: ['Em7', 'Bm7', 'Cmaj7'] },
      { label: 'Aメロ', chords: ['Em7', 'Bm7', 'Cmaj7', 'G', 'Cmaj7', 'Bm7'] },
      { label: 'Bメロ', chords: ['Em7', 'Am'] },
      { label: 'サビ', chords: ['Em7', 'D', 'C', 'Cmaj7', 'Am7/D'] },
      { label: 'アウトロ', chords: ['Em7', 'Bm7', 'Cmaj7'] },
    ],
    capo: 3,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', '結婚式'],
  },
  {
    id: 'song_059',
    title: 'First Love',
    artist: '宇多田ヒカル',
    year: 1999,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'o1sUaVJUeB0',
    sections: [
      { label: 'イントロ', chords: ['Bb', 'A', 'Cmaj7', 'Am7/D', 'G'] },
      { label: 'Aメロ', chords: ['Em', 'D', 'Em7', 'G', 'Cmaj7', 'Am7/D'] },
      { label: 'Bメロ', chords: ['Em', 'Gmaj7', 'Cmaj7', 'Am7/D', 'G'] },
      { label: 'サビ', chords: ['Em', 'Gmaj7', 'Cmaj7', 'Am7/D', 'D'] },
      { label: 'アウトロ', chords: ['Em', 'Gmaj7', 'Am7/D', 'Em7'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['定番', '弾き語り', '90s', 'バラード'],
  },
  {
    id: 'song_060',
    title: 'いつかのメリークリスマス',
    artist: 'B\'z',
    year: 1992,
    decade: '90s',
    genre: 'rock',
    youtubeId: 'QZFEnfBmfqg',
    sections: [
      { label: 'イントロ', chords: ['Cmaj7', 'D', 'Cmaj7', 'G', 'Bm7', 'Am7'] },
      { label: 'Aメロ', chords: ['Cmaj7', 'Bm7', 'Am7', 'D', 'Gmaj7'] },
      { label: 'Bメロ', chords: ['Am7', 'D', 'Gmaj7', 'Cmaj7', 'B7'] },
      { label: 'サビ', chords: ['Cmaj7', 'Bm7', 'Am7', 'Gmaj7', 'F#m7b5'] },
      { label: 'アウトロ', chords: ['Cmaj7', 'Bm7', 'Am7', 'D', 'Gmaj7'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['クリスマス', '定番', '弾き語り', 'バラード'],
  },
  {
    id: 'song_061',
    title: 'それが大事',
    artist: '大事MANブラザーズバンド',
    year: 1991,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'i-4in14x5y0',
    sections: [
      { label: 'イントロ', chords: ['Cmaj7', 'D', 'Cmaj7', 'G', 'Bm7', 'Am7'] },
      { label: 'Aメロ', chords: ['Cmaj7', 'Bm7', 'Am7', 'Gmaj7'] },
      { label: 'Bメロ', chords: ['Em7', 'D', 'C', 'G', 'Am7', 'Bm7'] },
      { label: 'サビ', chords: ['Cmaj7', 'Bm7', 'Am7', 'Gmaj7'] },
      { label: 'アウトロ', chords: ['Cmaj7', 'Bm7', 'Am7', 'D', 'Gmaj7'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['定番', '応援歌', '弾き語り'],
  },
  {
    id: 'song_062',
    title: '世界中の誰よりきっと',
    artist: '中山美穂 & WANDS',
    year: 1992,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'jrjBM0BnYeg',
    sections: [
      { label: 'イントロ', chords: ['A', 'D'] },
      { label: 'Aメロ', chords: ['A', 'Bm', 'F#m7', 'Bm7'] },
      { label: 'Bメロ', chords: ['Em7', 'A7', 'D', 'D/F#'] },
      { label: 'サビ', chords: ['D', 'C#m7-5', 'F#7', 'Bm'] },
      { label: 'アウトロ', chords: ['A'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', 'デュエット'],
  },
  {
    id: 'song_063',
    title: 'PRIDE',
    artist: '今井美樹',
    year: 1996,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'YdnrmS1h14A',
    sections: [
      { label: 'イントロ', chords: ['C', 'G/B', 'Am7', 'C/G', 'Fm', 'G', 'C'] },
      { label: 'Aメロ', chords: ['C', 'G/B', 'Am', 'C/G', 'Fm', 'G', 'C'] },
      { label: 'Bメロ', chords: ['Em7', 'Am7', 'Fm7b5', 'G', 'G7'] },
      { label: 'サビ', chords: ['Am7', 'Dm', 'Gsus4', 'G', 'C'] },
      { label: '間奏', chords: ['Fm7', 'G', 'C'] },
      { label: 'アウトロ', chords: ['C'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['バラード', '定番', '弾き語り'],
  },
]
