import { Song } from '@/types'

export const songs2000s: Song[] = [
  // ── 既存3曲 ──
  {
    id: 'song_007',
    title: '天体観測',
    artist: 'BUMP OF CHICKEN',
    year: 2001,
    decade: '2000s',
    genre: 'rock',
    youtubeId: 'j7CDb610Bg0',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'Am', 'D'] },
      { label: 'Bメロ', chords: ['Em', 'C', 'G', 'D', 'Em', 'C', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'C', 'G', 'Am', 'D'] },
    ],
    capo: 4,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '青春'],
  },
  {
    id: 'song_008',
    title: '粉雪',
    artist: 'レミオロメン',
    year: 2005,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: '1wxTksLZ1Mw',
    sections: [
      { label: 'イントロ', chords: ['C', 'G', 'Am', 'Em', 'F', 'C', 'G'] },
      { label: 'Aメロ', chords: ['C', 'G', 'Am', 'Em', 'F', 'C', 'G', 'G'] },
      { label: 'Bメロ', chords: ['F', 'C', 'G', 'G', 'Am', 'Em', 'F', 'G'] },
      { label: 'サビ', chords: ['F', 'G', 'C', 'Am', 'F', 'G', 'Am', 'G'] },
    ],
    capo: 4,
    difficulty: 'easy',
    tags: ['冬', '定番', '弾き語り'],
  },
  {
    id: 'song_009',
    title: '小さな恋のうた',
    artist: 'MONGOL800',
    year: 2001,
    decade: '2000s',
    genre: 'rock',
    youtubeId: 'JoJ6lnF07U4',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'C', 'D'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'C', 'D'] },
      { label: 'Bメロ', chords: ['Em', 'C', 'G', 'D', 'Em', 'C', 'Am', 'D'] },
      { label: 'サビ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'C', 'D'] },
    ],
    capo: 3,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '初心者向け'],
  },
  // ── 新規27曲 ──
  {
    id: 'song_064',
    title: 'ハナミズキ',
    artist: '一青窈',
    year: 2004,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'TngUo1gDNOg',
    sections: [
      { label: 'イントロ', chords: ['C', 'G', 'Am', 'F', 'C', 'G', 'F'] },
      { label: 'Aメロ', chords: ['C', 'G', 'Am', 'Em', 'F', 'C', 'G', 'G'] },
      { label: 'Bメロ', chords: ['Am', 'Em', 'F', 'C', 'Am', 'Em', 'F', 'G'] },
      { label: 'サビ', chords: ['C', 'G', 'Am', 'F', 'C', 'G', 'Am', 'F'] },
    ],
    capo: 4,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', '春'],
  },
  {
    id: 'song_065',
    title: 'さくら（独唱）',
    artist: '森山直太朗',
    year: 2003,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'p_2F2lKV9uA',
    sections: [
      { label: 'イントロ', chords: ['G', 'Am', 'Dsus4', 'D', 'G', 'Am', 'Dsus4', 'D'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'D', 'G', 'D'] },
      { label: 'Bメロ', chords: ['Em', 'C', 'G', 'D', 'Am', 'D', 'G', 'G'] },
      { label: 'サビ', chords: ['G', 'D', 'Em', 'Bm7', 'C', 'G', 'Am', 'D'] },
    ],
    capo: 1,
    difficulty: 'medium',
    tags: ['春', '定番', '弾き語り', '卒業式'],
  },
  {
    id: 'song_066',
    title: '栄光の架橋',
    artist: 'ゆず',
    year: 2004,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'PRJoAPH0ZGo',
    sections: [
      { label: 'イントロ', chords: ['C', 'G', 'Am', 'F'] },
      { label: 'Aメロ', chords: ['C', 'G', 'Am', 'Em', 'F', 'G', 'C', 'G'] },
      { label: 'Bメロ', chords: ['Am', 'Em', 'F', 'G', 'Am', 'Em', 'Dm', 'G'] },
      { label: 'サビ', chords: ['F', 'G', 'C', 'Am', 'F', 'G', 'Am', 'G'] },
    ],
    capo: 3,
    difficulty: 'easy',
    tags: ['応援歌', '定番', '弾き語り'],
  },
  {
    id: 'song_067',
    title: 'HOME',
    artist: 'コブクロ',
    year: 2005,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'C', 'G'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'Am', 'D'] },
      { label: 'Bメロ', chords: ['Em', 'G', 'C', 'D', 'Em', 'Am', 'D', 'D'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'C', 'G', 'Am', 'D'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_068',
    title: '蕾',
    artist: 'コブクロ',
    year: 2007,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'WPH1BLHKOJE',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'Am', 'D'] },
      { label: 'Bメロ', chords: ['Em', 'C', 'G', 'D', 'Em', 'Am', 'D', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'C', 'D', 'G', 'G'] },
    ],
    capo: 2,
    difficulty: 'medium',
    tags: ['バラード', '定番', '弾き語り'],
  },
  {
    id: 'song_069',
    title: '桜坂',
    artist: '福山雅治',
    year: 2000,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'AGYJ6jeu3p8',
    sections: [
      { label: 'イントロ', chords: ['Am', 'G', 'F', 'Em'] },
      { label: 'Aメロ', chords: ['Am', 'G', 'F', 'Em', 'Am', 'G', 'Dm', 'E'] },
      { label: 'Bメロ', chords: ['Dm', 'E', 'Am', 'G', 'F', 'G', 'Am', 'E'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'C', 'F', 'G', 'Am', 'E'] },
    ],
    capo: 2,
    difficulty: 'easy',
    tags: ['春', '定番', '弾き語り'],
  },
  {
    id: 'song_070',
    title: '道',
    artist: 'EXILE',
    year: 2002,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'VOPmfA-N4Rw',
    sections: [
      { label: 'イントロ', chords: ['C', 'G', 'Am', 'F'] },
      { label: 'Aメロ', chords: ['C', 'G', 'Am', 'F', 'C', 'G', 'F', 'G'] },
      { label: 'Bメロ', chords: ['Am', 'Em', 'F', 'G', 'Am', 'Em', 'F', 'G'] },
      { label: 'サビ', chords: ['F', 'G', 'C', 'Am', 'F', 'G', 'C', 'G'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', '応援歌'],
  },
  {
    id: 'song_071',
    title: 'TSUNAMI',
    artist: 'サザンオールスターズ',
    year: 2000,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'uOv48wstbgY',
    sections: [
      { label: 'イントロ', chords: ['G', 'Em', 'C', 'D'] },
      { label: 'Aメロ', chords: ['G', 'Em', 'Am', 'D', 'G', 'Em', 'Am', 'D'] },
      { label: 'Bメロ', chords: ['C', 'D', 'Bm7', 'Em', 'Am', 'D', 'G', 'D'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'Am', 'D', 'G', 'G'] },
    ],
    capo: 1,
    difficulty: 'medium',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_072',
    title: '世界に一つだけの花',
    artist: 'SMAP',
    year: 2003,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'qZq-q75KeMw',
    sections: [
      { label: 'イントロ', chords: ['C', 'F', 'G', 'Am'] },
      { label: 'Aメロ', chords: ['C', 'G', 'Am', 'F', 'C', 'G', 'F', 'G'] },
      { label: 'Bメロ', chords: ['Am', 'Em', 'F', 'G', 'Am', 'Em', 'F', 'G'] },
      { label: 'サビ', chords: ['F', 'G', 'C', 'Am', 'F', 'G', 'C', 'C'] },
    ],
    capo: 5,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '初心者向け'],
  },
  {
    id: 'song_073',
    title: '明日への扉',
    artist: 'I WiSH',
    year: 2001,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'yPCno5Tk4ik',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'G', 'D', 'D'] },
      { label: 'Bメロ', chords: ['C', 'G', 'D', 'D', 'C', 'G', 'Am', 'D'] },
      { label: 'サビ', chords: ['G', 'D', 'Em', 'Bm7', 'C', 'G', 'Am', 'D'] },
    ],
    capo: 2,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '応援歌'],
  },
  {
    id: 'song_074',
    title: '花火',
    artist: 'aiko',
    year: 2001,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'iqGHxcTPRfI',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C', 'Am', 'G', 'D', 'D'] },
      { label: 'Bメロ', chords: ['C', 'G', 'Am', 'D', 'C', 'G', 'Am', 'D'] },
      { label: 'サビ', chords: ['Em', 'C', 'G', 'D', 'Em', 'C', 'Am', 'D'] },
    ],
    capo: 3,
    difficulty: 'medium',
    tags: ['夏', '定番', '弾き語り'],
  },
  {
    id: 'song_075',
    title: 'さくらんぼ',
    artist: '大塚愛',
    year: 2003,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'upODO6OuOOk',
    sections: [
      { label: 'イントロ', chords: ['C', 'G', 'Am', 'F'] },
      { label: 'Aメロ', chords: ['C', 'G', 'Am', 'F', 'C', 'G', 'F', 'G'] },
      { label: 'Bメロ', chords: ['Am', 'F', 'C', 'G', 'Am', 'F', 'Dm', 'G'] },
      { label: 'サビ', chords: ['C', 'G', 'Am', 'F', 'C', 'G', 'F', 'G'] },
    ],
    capo: 4,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_076',
    title: 'プラネタリウム',
    artist: '大塚愛',
    year: 2004,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 't6xdg6TKbyQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'Em', 'C', 'D'] },
      { label: 'Aメロ', chords: ['G', 'Em', 'Am', 'D', 'G', 'Em', 'Am', 'D'] },
      { label: 'Bメロ', chords: ['C', 'D', 'G', 'G', 'C', 'D', 'Em', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'C', 'D', 'G', 'G'] },
    ],
    capo: 3,
    difficulty: 'easy',
    tags: ['バラード', '弾き語り'],
  },
  {
    id: 'song_077',
    title: 'HANABI',
    artist: 'Mr.Children',
    year: 2008,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'EXxaBXKjl6Q',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'Am', 'D'] },
      { label: 'Bメロ', chords: ['Em', 'Bm7', 'C', 'G', 'Am', 'D', 'G', 'D'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'C', 'G', 'Am', 'D'] },
    ],
    capo: 2,
    difficulty: 'medium',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_078',
    title: 'しるし',
    artist: 'Mr.Children',
    year: 2006,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'xXA5StMti8c',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Bm7', 'Em'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Bm7', 'Em', 'C', 'G', 'Am', 'D'] },
      { label: 'Bメロ', chords: ['Em', 'C', 'G', 'D', 'Am', 'D', 'Em', 'D'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'Am', 'D', 'G', 'G'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['バラード', '定番', '弾き語り'],
  },
  {
    id: 'song_079',
    title: 'リライト',
    artist: 'ASIAN KUNG-FU GENERATION',
    year: 2004,
    decade: '2000s',
    genre: 'rock',
    youtubeId: 'cr8magEp0Ho',
    sections: [
      { label: 'イントロ', chords: ['Am', 'Em', 'Dm', 'Am'] },
      { label: 'Aメロ', chords: ['Am', 'F', 'C', 'G', 'Am', 'F', 'Dm', 'E'] },
      { label: 'Bメロ', chords: ['Dm', 'Am', 'F', 'G', 'Dm', 'E', 'Am', 'E'] },
      { label: 'サビ', chords: ['Am', 'F', 'G', 'C', 'Am', 'F', 'G', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['ロック', '定番', '弾き語り'],
  },
  {
    id: 'song_080',
    title: 'ループ',
    artist: 'ASIAN KUNG-FU GENERATION',
    year: 2004,
    decade: '2000s',
    genre: 'rock',
    youtubeId: 'Aq6gMHBobcA',
    sections: [
      { label: 'イントロ', chords: ['G', 'Em', 'C', 'D'] },
      { label: 'Aメロ', chords: ['G', 'Em', 'Am', 'D', 'G', 'Em', 'C', 'D'] },
      { label: 'Bメロ', chords: ['C', 'G', 'D', 'D', 'C', 'G', 'Am', 'D'] },
      { label: 'サビ', chords: ['Em', 'C', 'G', 'D', 'Em', 'C', 'Am', 'D'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['ロック', '弾き語り'],
  },
  {
    id: 'song_081',
    title: 'カルマ',
    artist: 'BUMP OF CHICKEN',
    year: 2004,
    decade: '2000s',
    genre: 'rock',
    youtubeId: 'mTdcxQZcQAE',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'Am', 'D'] },
      { label: 'Bメロ', chords: ['Em', 'C', 'G', 'D', 'Am', 'D', 'Em', 'D'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'C', 'G', 'Am', 'D'] },
    ],
    capo: 4,
    difficulty: 'medium',
    tags: ['ロック', '定番', '弾き語り'],
  },
  {
    id: 'song_082',
    title: '3月9日',
    artist: 'レミオロメン',
    year: 2004,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'UNRJyBHziX4',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'Am', 'D'] },
      { label: 'Bメロ', chords: ['Am', 'D', 'G', 'G', 'Am', 'D', 'Em', 'D'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'C', 'G', 'Am', 'D'] },
    ],
    capo: 2,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '卒業式'],
  },
  {
    id: 'song_083',
    title: 'ふたりごと',
    artist: 'RADWIMPS',
    year: 2006,
    decade: '2000s',
    genre: 'rock',
    youtubeId: 'gmLXEmCExIE',
    sections: [
      { label: 'イントロ', chords: ['Am', 'F', 'C', 'G'] },
      { label: 'Aメロ', chords: ['Am', 'F', 'C', 'G', 'Am', 'F', 'Dm', 'G'] },
      { label: 'Bメロ', chords: ['F', 'G', 'Am', 'Am', 'F', 'G', 'C', 'G'] },
      { label: 'サビ', chords: ['C', 'G', 'Am', 'F', 'C', 'G', 'F', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['ロック', '弾き語り'],
  },
  {
    id: 'song_084',
    title: 'ありがとう',
    artist: 'いきものがかり',
    year: 2010,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'VZBU8LvZ91Q',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'Am', 'D'] },
      { label: 'Bメロ', chords: ['C', 'G', 'Bm7', 'Em', 'Am', 'D', 'G', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'C', 'D', 'G', 'G'] },
    ],
    capo: 2,
    difficulty: 'medium',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_085',
    title: 'Story',
    artist: 'AI',
    year: 2007,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'nMROhyihehU',
    sections: [
      { label: 'イントロ', chords: ['Am', 'F', 'G', 'C'] },
      { label: 'Aメロ', chords: ['Am', 'F', 'C', 'G', 'Am', 'F', 'Dm', 'G'] },
      { label: 'Bメロ', chords: ['F', 'G', 'Am', 'Em', 'F', 'G', 'C', 'G'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'C', 'F', 'G', 'C', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_086',
    title: '桜',
    artist: 'コブクロ',
    year: 2003,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'Dsdxxrnz1AQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'Em', 'C', 'D'] },
      { label: 'Aメロ', chords: ['G', 'Em', 'C', 'D', 'G', 'Em', 'Am', 'D'] },
      { label: 'Bメロ', chords: ['C', 'D', 'Em', 'Bm7', 'Am', 'D', 'G', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'C', 'D', 'G', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['春', '定番', '弾き語り'],
  },
  {
    id: 'song_087',
    title: '愛し君へ',
    artist: '森山直太朗',
    year: 2004,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: '2TWJOvc-css',
    sections: [
      { label: 'イントロ', chords: ['G', 'Am', 'Dsus4', 'D'] },
      { label: 'Aメロ', chords: ['G', 'Em', 'Am', 'D', 'G', 'Em', 'C', 'D'] },
      { label: 'Bメロ', chords: ['C', 'G', 'Am', 'D', 'C', 'G', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G', 'G'] },
    ],
    capo: 2,
    difficulty: 'medium',
    tags: ['バラード', '弾き語り'],
  },
  {
    id: 'song_088',
    title: 'フィクション',
    artist: 'aiko',
    year: 2002,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Am', 'G', 'F', 'E'] },
      { label: 'Aメロ', chords: ['Am', 'G', 'F', 'E', 'Am', 'G', 'Dm', 'E'] },
      { label: 'Bメロ', chords: ['Dm', 'E', 'Am', 'G', 'F', 'G', 'C', 'E'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'C', 'F', 'G', 'Am', 'E'] },
    ],
    capo: 2,
    difficulty: 'medium',
    tags: ['弾き語り'],
  },
  {
    id: 'song_089',
    title: 'ガラスのブルース',
    artist: 'BUMP OF CHICKEN',
    year: 2000,
    decade: '2000s',
    genre: 'rock',
    youtubeId: 'bnlstlAfdJU',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Am', 'C', 'G', 'D', 'Am', 'D'] },
      { label: 'Bメロ', chords: ['Em', 'C', 'Am', 'D', 'Em', 'C', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'C', 'D', 'G', 'G'] },
    ],
    capo: 4,
    difficulty: 'easy',
    tags: ['ロック', '弾き語り'],
  },
  {
    id: 'song_090',
    title: 'またあした',
    artist: 'ゆず',
    year: 2003,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: '2EdarX_Lf2Q',
    sections: [
      { label: 'イントロ', chords: ['G', 'C', 'G', 'D'] },
      { label: 'Aメロ', chords: ['G', 'D', 'C', 'G', 'G', 'D', 'Am', 'D'] },
      { label: 'Bメロ', chords: ['Em', 'Am', 'C', 'D', 'Em', 'Am', 'D', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'C', 'D', 'G', 'G'] },
    ],
    capo: 3,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
]
