import { Song } from '@/types'

export const songs2000s: Song[] = [
  // ── 既存3曲 ──
  {
    id: 'song_007',
    title: '天体観測',
    artist: 'BUMP OF CHICKEN',
    year: 2001,
    decade: '2000s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'Em', 'C'] },
      { label: 'Bメロ', chords: ['Em', 'C', 'G', 'D'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'C', 'G', 'D'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '青春'],
  },
  {
    id: 'song_008',
    title: '粉雪',
    artist: 'レミオロメン',
    year: 2005,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'C', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['冬', '定番', '弾き語り'],
  },
  {
    id: 'song_009',
    title: '小さな恋のうた',
    artist: 'MONGOL800',
    year: 2001,
    decade: '2000s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['C', 'G', 'Am', 'F'] },
      { label: 'Aメロ', chords: ['C', 'G', 'Am', 'F', 'C', 'G', 'F', 'G'] },
      { label: 'サビ', chords: ['F', 'G', 'C', 'Am', 'F', 'G', 'C'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '初心者向け'],
  },
  // ── 新規27曲 ──
  {
    id: 'song_064',
    title: 'ハナミズキ',
    artist: '一青窈',
    year: 2004,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Bm', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'Bm', 'C', 'D'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', '春'],
  },
  {
    id: 'song_065',
    title: 'さくら（独唱）',
    artist: '森山直太朗',
    year: 2003,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 2,
    difficulty: 'easy',
    tags: ['春', '定番', '弾き語り', '卒業式'],
  },
  {
    id: 'song_066',
    title: '栄光の架橋',
    artist: 'ゆず',
    year: 2004,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['応援歌', '定番', '弾き語り'],
  },
  {
    id: 'song_067',
    title: 'HOME',
    artist: 'コブクロ',
    year: 2005,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_068',
    title: '蕾',
    artist: 'コブクロ',
    year: 2007,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Bm', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'Bm', 'C', 'D'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['バラード', '定番', '弾き語り'],
  },
  {
    id: 'song_069',
    title: '桜坂',
    artist: '福山雅治',
    year: 2000,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Am', 'G', 'F', 'Em'] },
      { label: 'Aメロ', chords: ['Am', 'G', 'F', 'Em', 'Dm', 'G', 'C'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'C', 'F', 'G', 'C'] },
    ],
    capo: 2,
    difficulty: 'easy',
    tags: ['春', '定番', '弾き語り'],
  },
  {
    id: 'song_070',
    title: '道',
    artist: 'EXILE',
    year: 2002,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Bm', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', '応援歌'],
  },
  {
    id: 'song_071',
    title: 'TSUNAMI',
    artist: 'サザンオールスターズ',
    year: 2000,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Am', 'C', 'F', 'G'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'Am', 'F', 'G'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_072',
    title: '世界に一つだけの花',
    artist: 'SMAP',
    year: 2003,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['C', 'G', 'Am', 'F'] },
      { label: 'Aメロ', chords: ['C', 'G', 'Am', 'F', 'Dm', 'Em', 'G'] },
      { label: 'サビ', chords: ['F', 'G', 'C', 'Am', 'Dm', 'G', 'C'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '初心者向け'],
  },
  {
    id: 'song_073',
    title: '明日への扉',
    artist: 'I WiSH',
    year: 2001,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '応援歌'],
  },
  {
    id: 'song_074',
    title: '花火',
    artist: 'aiko',
    year: 2001,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'F', 'G'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'Am', 'F', 'G'] },
    ],
    capo: 3,
    difficulty: 'medium',
    tags: ['夏', '定番', '弾き語り'],
  },
  {
    id: 'song_075',
    title: 'さくらんぼ',
    artist: '大塚愛',
    year: 2003,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'F', 'G', 'C'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'Am', 'F', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_076',
    title: 'プラネタリウム',
    artist: '大塚愛',
    year: 2004,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'Em', 'C', 'D'] },
      { label: 'Aメロ', chords: ['G', 'Em', 'C', 'D', 'Am', 'G'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['バラード', '弾き語り'],
  },
  {
    id: 'song_077',
    title: 'HANABI',
    artist: 'Mr.Children',
    year: 2008,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Bm', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'Bm', 'C', 'D'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_078',
    title: 'しるし',
    artist: 'Mr.Children',
    year: 2006,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['バラード', '定番', '弾き語り'],
  },
  {
    id: 'song_079',
    title: 'リライト',
    artist: 'ASIAN KUNG-FU GENERATION',
    year: 2004,
    decade: '2000s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Am', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Am', 'C', 'G', 'D', 'Em', 'C'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['ロック', '定番', '弾き語り'],
  },
  {
    id: 'song_080',
    title: 'ループ',
    artist: 'ASIAN KUNG-FU GENERATION',
    year: 2004,
    decade: '2000s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'Em', 'C', 'D'] },
      { label: 'Aメロ', chords: ['G', 'Em', 'Am', 'D', 'G', 'Em', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['ロック', '弾き語り'],
  },
  {
    id: 'song_081',
    title: 'カルマ',
    artist: 'BUMP OF CHICKEN',
    year: 2004,
    decade: '2000s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Bm', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'Bm', 'C', 'D'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['ロック', '定番', '弾き語り'],
  },
  {
    id: 'song_082',
    title: '3月9日',
    artist: 'レミオロメン',
    year: 2004,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '卒業式'],
  },
  {
    id: 'song_083',
    title: 'ふたりごと',
    artist: 'RADWIMPS',
    year: 2006,
    decade: '2000s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['ロック', '弾き語り'],
  },
  {
    id: 'song_084',
    title: 'ありがとう',
    artist: 'いきものがかり',
    year: 2010,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Bm', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'Bm', 'C', 'D'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_085',
    title: 'Story',
    artist: 'AI',
    year: 2007,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_086',
    title: '桜',
    artist: 'コブクロ',
    year: 2003,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'F', 'G', 'C'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'F', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['春', '定番', '弾き語り'],
  },
  {
    id: 'song_087',
    title: '愛し君へ',
    artist: '森山直太朗',
    year: 2004,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'Em', 'C', 'D'] },
      { label: 'Aメロ', chords: ['G', 'Em', 'Am', 'Bm', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['バラード', '弾き語り'],
  },
  {
    id: 'song_088',
    title: 'フィクション',
    artist: 'aiko',
    year: 2002,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Am', 'G', 'F', 'E'] },
      { label: 'Aメロ', chords: ['Am', 'G', 'F', 'C', 'Dm', 'G'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'C', 'F', 'G', 'C'] },
    ],
    capo: 2,
    difficulty: 'medium',
    tags: ['弾き語り'],
  },
  {
    id: 'song_089',
    title: 'ガラスのブルース',
    artist: 'BUMP OF CHICKEN',
    year: 2000,
    decade: '2000s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['ロック', '弾き語り'],
  },
  {
    id: 'song_090',
    title: 'またあした',
    artist: 'ゆず',
    year: 2003,
    decade: '2000s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
]
