import { Song } from '@/types'

export const songs80s: Song[] = [
  // ── 既存3曲 ──
  {
    id: 'song_001',
    title: 'I LOVE YOU',
    artist: '尾崎豊',
    year: 1983,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Am', 'F', 'G', 'C'] },
      { label: 'Aメロ', chords: ['Am', 'F', 'G', 'C', 'Am', 'F', 'G', 'E'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'C', 'F', 'G', 'C'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_002',
    title: 'MARIONETTE',
    artist: 'BOØWY',
    year: 1985,
    decade: '80s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['E', 'A', 'B'] },
      { label: 'Aメロ', chords: ['E', 'A', 'E', 'B'] },
      { label: 'サビ', chords: ['A', 'B', 'E', 'C#m', 'A', 'B', 'E'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['ロック', '定番'],
  },
  {
    id: 'song_003',
    title: '真夏の果実',
    artist: 'サザンオールスターズ',
    year: 1990,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['C', 'G', 'Am', 'Em', 'F', 'G', 'C'] },
      { label: 'Aメロ', chords: ['C', 'G', 'Am', 'Em', 'F', 'G', 'C'] },
      { label: 'サビ', chords: ['F', 'G', 'Em', 'Am', 'F', 'G', 'C'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['夏', '定番', '弾き語り'],
  },
  // ── 新規27曲 ──
  {
    id: 'song_010',
    title: '卒業',
    artist: '尾崎豊',
    year: 1985,
    decade: '80s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Am', 'G', 'F', 'E'] },
      { label: 'Aメロ', chords: ['Am', 'G', 'F', 'E', 'Am', 'G', 'F', 'G'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'E', 'F', 'G', 'Am'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '青春'],
  },
  {
    id: 'song_011',
    title: '15の夜',
    artist: '尾崎豊',
    year: 1983,
    decade: '80s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Am', 'G', 'F', 'E'] },
      { label: 'Aメロ', chords: ['Am', 'G', 'F', 'E', 'Am', 'G', 'F', 'E'] },
      { label: 'Bメロ', chords: ['C', 'G', 'F', 'G', 'C', 'G', 'Dm', 'E'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'G', 'F', 'G', 'Am'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '青春'],
  },
  {
    id: 'song_012',
    title: '乾杯',
    artist: '長渕剛',
    year: 1980,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'C', 'G'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'C', 'G'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'C', 'G', 'D', 'G'] },
    ],
    capo: 3,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '宴会'],
  },
  {
    id: 'song_013',
    title: 'さよなら',
    artist: 'オフコース',
    year: 1982,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'Em', 'C', 'D'] },
      { label: 'Aメロ', chords: ['G', 'Em', 'Am', 'D', 'G', 'Em', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'C', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['バラード', '定番', '弾き語り'],
  },
  {
    id: 'song_014',
    title: 'SOMEDAY',
    artist: '佐野元春',
    year: 1982,
    decade: '80s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['C', 'Am', 'Dm7', 'G7'] },
      { label: 'Aメロ', chords: ['C', 'Am', 'F', 'G', 'C', 'Am', 'Em', 'G'] },
      { label: 'Bメロ', chords: ['Am', 'Em', 'F', 'G', 'Am', 'G', 'E7', 'Am'] },
      { label: 'サビ', chords: ['C', 'G', 'Am', 'F', 'Dm7', 'G7', 'C'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '80s', '弾き語り'],
  },
  {
    id: 'song_015',
    title: '涙のリクエスト',
    artist: 'チェッカーズ',
    year: 1984,
    decade: '80s',
    genre: 'pops',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['C', 'G', 'Am', 'F'] },
      { label: 'Aメロ', chords: ['C', 'G', 'Am', 'F', 'Dm', 'G', 'C'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'C', 'F', 'G', 'C'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_016',
    title: 'ワインレッドの心',
    artist: '安全地帯',
    year: 1983,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Am', 'Dm', 'G', 'C'] },
      { label: 'Aメロ', chords: ['Am', 'Dm', 'G', 'C', 'Am', 'Dm', 'E', 'Am'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'E', 'F', 'G', 'Am'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['バラード', '定番', '弾き語り'],
  },
  {
    id: 'song_017',
    title: '恋の予感',
    artist: '安全地帯',
    year: 1985,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['C', 'G', 'Am', 'Em'] },
      { label: 'Aメロ', chords: ['C', 'G', 'Am', 'Em', 'F', 'Dm', 'G'] },
      { label: 'サビ', chords: ['F', 'G', 'C', 'Am', 'F', 'G', 'C'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['バラード', '定番'],
  },
  {
    id: 'song_018',
    title: 'Get Wild',
    artist: 'TM NETWORK',
    year: 1987,
    decade: '80s',
    genre: 'pops',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Am', 'G', 'F', 'E'] },
      { label: 'Aメロ', chords: ['Am', 'G', 'F', 'E', 'Am', 'G', 'F', 'E'] },
      { label: 'サビ', chords: ['Dm', 'G', 'C', 'Am', 'Dm', 'G', 'Am'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '80s'],
  },
  {
    id: 'song_019',
    title: 'J.BOY',
    artist: '浜田省吾',
    year: 1986,
    decade: '80s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'C', 'G', 'G', 'D', 'C', 'D'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'C', 'G'] },
      { label: 'Bメロ', chords: ['Am', 'G', 'C', 'D', 'Am', 'G', 'D', 'D'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'C', 'G', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', 'ロック'],
  },
  {
    id: 'song_020',
    title: '悲しみは雪のように',
    artist: '浜田省吾',
    year: 1992,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'Em', 'Am', 'D'] },
      { label: 'Aメロ', chords: ['G', 'Em', 'Am', 'D', 'G', 'Em', 'Am', 'D'] },
      { label: 'Bメロ', chords: ['Am', 'Em', 'F', 'G', 'Dm', 'G', 'C', 'G'] },
      { label: 'サビ', chords: ['C', 'G', 'Am', 'Em', 'F', 'G', 'C'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['バラード', '弾き語り', '冬'],
  },
  {
    id: 'song_021',
    title: 'DREAMIN\'',
    artist: 'BOØWY',
    year: 1986,
    decade: '80s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['D', 'A', 'Bm', 'G'] },
      { label: 'Aメロ', chords: ['D', 'A', 'Bm', 'G', 'D', 'A', 'E'] },
      { label: 'サビ', chords: ['G', 'A', 'D', 'Bm', 'G', 'A', 'D'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['ロック', '定番'],
  },
  {
    id: 'song_022',
    title: '駅',
    artist: '竹内まりや',
    year: 1987,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'Em', 'Am', 'D'] },
      { label: 'Aメロ', chords: ['G', 'Em', 'Am', 'D', 'G', 'Em', 'Am', 'D'] },
      { label: 'Bメロ', chords: ['Em', 'Am', 'D7', 'G', 'Em', 'Am', 'D', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['バラード', '定番', '弾き語り'],
  },
  {
    id: 'song_023',
    title: 'ギザギザハートの子守唄',
    artist: 'チェッカーズ',
    year: 1983,
    decade: '80s',
    genre: 'pops',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['A', 'D', 'E', 'A'] },
      { label: 'Aメロ', chords: ['A', 'D', 'E', 'A', 'C#m', 'Bm', 'E'] },
      { label: 'サビ', chords: ['D', 'E', 'A', 'C#m', 'D', 'E', 'A'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '80s'],
  },
  {
    id: 'song_024',
    title: '雨上がりの夜空に',
    artist: 'RCサクセション',
    year: 1980,
    decade: '80s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'C', 'G', 'D'] },
      { label: 'Aメロ', chords: ['G', 'C', 'G', 'D', 'G', 'C', 'D', 'G'] },
      { label: 'サビ', chords: ['Em', 'Am', 'G', 'D', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['ロック', '定番'],
  },
  {
    id: 'song_025',
    title: 'クリスマス・イブ',
    artist: '山下達郎',
    year: 1983,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['C', 'Am', 'Dm', 'G'] },
      { label: 'Aメロ', chords: ['C', 'Am', 'Dm', 'G', 'Em', 'Am', 'Dm', 'G'] },
      { label: 'サビ', chords: ['F', 'G', 'Em', 'Am', 'Dm', 'G', 'C'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['クリスマス', '定番', '弾き語り'],
  },
  {
    id: 'song_026',
    title: '少女A',
    artist: '中森明菜',
    year: 1982,
    decade: '80s',
    genre: 'pops',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Am', 'G', 'F', 'Em'] },
      { label: 'Aメロ', chords: ['Am', 'G', 'F', 'E', 'Am', 'G', 'Dm', 'E'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'E', 'F', 'G', 'Am'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '80s'],
  },
  {
    id: 'song_027',
    title: 'Forget-me-not',
    artist: '尾崎豊',
    year: 1986,
    decade: '80s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Am', 'G', 'F', 'E'] },
      { label: 'Aメロ', chords: ['Am', 'G', 'F', 'E', 'Am', 'G', 'F', 'G'] },
      { label: 'Bメロ', chords: ['C', 'G', 'F', 'G', 'C', 'G', 'Dm', 'E'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'E', 'F', 'G', 'C'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['弾き語り', '青春', '尾崎豊'],
  },
  {
    id: 'song_028',
    title: '恋',
    artist: '松山千春',
    year: 1980,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'D', 'G'] },
      { label: 'Bメロ', chords: ['Am', 'D', 'G', 'Em', 'C', 'G', 'D', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 2,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', 'フォーク'],
  },
  {
    id: 'song_029',
    title: 'ルビーの指環',
    artist: '寺尾聡',
    year: 1981,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Am', 'Dm', 'G', 'C'] },
      { label: 'Aメロ', chords: ['Am', 'Dm', 'G', 'C', 'Am', 'Dm', 'E'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'E', 'F', 'G', 'Am'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['バラード', '定番'],
  },
  {
    id: 'song_030',
    title: 'もしもピアノが弾けたなら',
    artist: '西田敏行',
    year: 1981,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['C', 'G', 'Am', 'F'] },
      { label: 'Aメロ', chords: ['C', 'G', 'Am', 'F', 'Dm', 'G', 'C'] },
      { label: 'サビ', chords: ['F', 'G', 'C', 'Am', 'Dm', 'G', 'C'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_031',
    title: '北の国から',
    artist: 'さだまさし',
    year: 1981,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'Am'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'D', 'G'] },
      { label: 'サビ', chords: ['C', 'G', 'Am', 'Em', 'C', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_032',
    title: '夏の終わりのハーモニー',
    artist: '井上陽水 & 安全地帯',
    year: 1986,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'Bm', 'C', 'G', 'A', 'D'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Bm', 'C', 'G', 'Am', 'D'] },
      { label: 'Bメロ', chords: ['Em', 'Bm', 'Am', 'D', 'Em', 'C', 'D', 'D'] },
      { label: 'サビ', chords: ['G', 'A', 'D', 'Bm', 'G', 'D', 'A', 'D'] },
    ],
    capo: 2,
    difficulty: 'medium',
    tags: ['バラード', '夏', '定番', 'デュエット'],
  },
  {
    id: 'song_033',
    title: 'セーラー服と機関銃',
    artist: '薬師丸ひろ子',
    year: 1981,
    decade: '80s',
    genre: 'pops',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'C', 'G'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Am', 'C', 'G', 'D', 'Em', 'C'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '80s'],
  },
  {
    id: 'song_034',
    title: 'SELF CONTROL',
    artist: 'TM NETWORK',
    year: 1987,
    decade: '80s',
    genre: 'pops',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Am', 'G', 'F', 'E'] },
      { label: 'Aメロ', chords: ['Am', 'G', 'F', 'C', 'Dm', 'G', 'Am'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'C', 'F', 'G', 'Am'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['80s'],
  },
  {
    id: 'song_035',
    title: '時間よ止まれ',
    artist: '矢沢永吉',
    year: 1978,
    decade: '80s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Am', 'G', 'F', 'E'] },
      { label: 'Aメロ', chords: ['Am', 'G', 'F', 'E', 'Am', 'G', 'Dm', 'E'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'G', 'F', 'E', 'Am'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_036',
    title: 'ひとり',
    artist: '尾崎豊',
    year: 1984,
    decade: '80s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Am', 'G', 'F', 'E'] },
      { label: 'Aメロ', chords: ['Am', 'G', 'F', 'E', 'C', 'G', 'F', 'E'] },
      { label: 'サビ', chords: ['F', 'G', 'C', 'Am', 'F', 'G', 'Am'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['弾き語り', '青春'],
  },
]
