import { Song } from '@/types'

export const songs90s: Song[] = [
  // ── 既存3曲 ──
  {
    id: 'song_004',
    title: 'チェリー',
    artist: 'スピッツ',
    year: 1996,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['D', 'A', 'G', 'A'] },
      { label: 'Aメロ', chords: ['D', 'A', 'G', 'A', 'D', 'A', 'G', 'A'] },
      { label: 'Bメロ', chords: ['G', 'A', 'Bm', 'G', 'A'] },
      { label: 'サビ', chords: ['D', 'A', 'G', 'A', 'D', 'A', 'G', 'A'] },
    ],
    capo: 3,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '初心者向け'],
  },
  {
    id: 'song_005',
    title: 'Tomorrow never knows',
    artist: 'Mr.Children',
    year: 1994,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['D', 'A', 'Bm', 'G'] },
      { label: 'Aメロ', chords: ['D', 'A', 'Bm', 'G', 'D', 'A', 'G'] },
      { label: 'サビ', chords: ['G', 'A', 'D', 'Bm', 'G', 'A', 'D'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_006',
    title: 'HOWEVER',
    artist: 'GLAY',
    year: 1997,
    decade: '90s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'Em', 'C', 'D'] },
      { label: 'Aメロ', chords: ['G', 'Em', 'C', 'D'] },
      { label: 'サビ', chords: ['Em', 'C', 'G', 'D', 'Em', 'C', 'D'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['バラード', '定番', '弾き語り'],
  },
  // ── 新規27曲 ──
  {
    id: 'song_037',
    title: 'ロビンソン',
    artist: 'スピッツ',
    year: 1995,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'Bm', 'Am'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'C', 'D', 'G'] },
    ],
    capo: 2,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '初心者向け'],
  },
  {
    id: 'song_038',
    title: '空も飛べるはず',
    artist: 'スピッツ',
    year: 1994,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 3,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_039',
    title: '名もなき詩',
    artist: 'Mr.Children',
    year: 1996,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C', 'Bm', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'Bm', 'C', 'D'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_040',
    title: 'CROSS ROAD',
    artist: 'Mr.Children',
    year: 1993,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'C', 'G', 'D', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_041',
    title: '負けないで',
    artist: 'ZARD',
    year: 1993,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 2,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '応援歌'],
  },
  {
    id: 'song_042',
    title: '揺れる想い',
    artist: 'ZARD',
    year: 1993,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Em', 'G', 'Am', 'D'] },
      { label: 'Aメロ', chords: ['Em', 'G', 'Am', 'D', 'Em', 'G', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_043',
    title: 'ラブ・ストーリーは突然に',
    artist: '小田和正',
    year: 1991,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['C', 'G', 'Am', 'F'] },
      { label: 'Aメロ', chords: ['C', 'G', 'Am', 'F', 'Em', 'Dm', 'G'] },
      { label: 'サビ', chords: ['F', 'G', 'C', 'Am', 'Dm', 'G', 'C'] },
    ],
    capo: 3,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '初心者向け'],
  },
  {
    id: 'song_044',
    title: 'どんなときも。',
    artist: '槇原敬之',
    year: 1991,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'Em', 'C', 'D'] },
      { label: 'Aメロ', chords: ['G', 'Em', 'Am', 'D', 'G', 'Em', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'Bm', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_045',
    title: 'もう恋なんてしない',
    artist: '槇原敬之',
    year: 1992,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'Em', 'C', 'D'] },
      { label: 'Aメロ', chords: ['G', 'Em', 'Am', 'D', 'G', 'Em', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_046',
    title: '遠く遠く',
    artist: '槇原敬之',
    year: 1992,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'Em', 'C', 'D'] },
      { label: 'Aメロ', chords: ['G', 'Em', 'C', 'D', 'G', 'Em', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'C', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_047',
    title: 'Hello, Again 〜昔からある場所〜',
    artist: 'My Little Lover',
    year: 1995,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Am', 'G', 'F', 'E'] },
      { label: 'Aメロ', chords: ['Am', 'G', 'F', 'E', 'Am', 'G', 'Dm', 'E'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'E', 'F', 'G', 'Am'] },
    ],
    capo: 3,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_048',
    title: 'Tomorrow',
    artist: '岡本真夜',
    year: 1995,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'Am', 'C', 'D'] },
      { label: 'Aメロ', chords: ['G', 'Am', 'C', 'D', 'Em', 'Am', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '応援歌'],
  },
  {
    id: 'song_049',
    title: 'One more time, One more chance',
    artist: '山崎まさよし',
    year: 1997,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Em', 'C', 'G', 'D'] },
      { label: 'Aメロ', chords: ['Em', 'C', 'G', 'D', 'Am', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['バラード', '定番', '弾き語り'],
  },
  {
    id: 'song_050',
    title: '少年時代',
    artist: '井上陽水',
    year: 1990,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'Em', 'Am', 'D'] },
      { label: 'Aメロ', chords: ['G', 'Em', 'C', 'D', 'Bm', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'G', 'Am', 'Em', 'C', 'D', 'G'] },
    ],
    capo: 2,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', '青春'],
  },
  {
    id: 'song_051',
    title: 'SAY YES',
    artist: 'CHAGE and ASKA',
    year: 1991,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'Bm', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'Bm', 'C', 'D'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_052',
    title: '君がいるだけで',
    artist: '米米CLUB',
    year: 1992,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['C', 'G', 'Am', 'F'] },
      { label: 'Aメロ', chords: ['C', 'G', 'Am', 'F', 'Dm', 'Em', 'G'] },
      { label: 'サビ', chords: ['F', 'G', 'C', 'Am', 'Dm', 'G', 'C'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_053',
    title: 'らいおんハート',
    artist: 'SMAP',
    year: 1999,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_054',
    title: 'セロリ',
    artist: 'SMAP',
    year: 1998,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['C', 'G', 'Am', 'Em'] },
      { label: 'Aメロ', chords: ['C', 'G', 'Am', 'Em', 'F', 'G', 'C'] },
      { label: 'サビ', chords: ['F', 'G', 'C', 'Em', 'Am', 'G', 'C'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_055',
    title: 'DEPARTURES',
    artist: 'globe',
    year: 1996,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Bm', 'G', 'D', 'A'] },
      { label: 'Aメロ', chords: ['Bm', 'G', 'D', 'A', 'Em', 'G', 'A'] },
      { label: 'サビ', chords: ['G', 'A', 'D', 'Bm', 'G', 'A', 'D'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '90s'],
  },
  {
    id: 'song_056',
    title: 'ズルい女',
    artist: 'シャ乱Q',
    year: 1994,
    decade: '90s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['D', 'A', 'Bm', 'G'] },
      { label: 'Aメロ', chords: ['D', 'A', 'Bm', 'G', 'E', 'A'] },
      { label: 'サビ', chords: ['G', 'A', 'D', 'Bm', 'G', 'A', 'D'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '90s'],
  },
  {
    id: 'song_057',
    title: '空と君のあいだに',
    artist: '中島みゆき',
    year: 1994,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Am', 'G', 'F', 'C'] },
      { label: 'Aメロ', chords: ['Am', 'G', 'F', 'Em', 'Dm', 'G'] },
      { label: 'サビ', chords: ['F', 'G', 'Am', 'C', 'F', 'G', 'C'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_058',
    title: '糸',
    artist: '中島みゆき',
    year: 1992,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Em', 'C', 'G', 'D'] },
      { label: 'Aメロ', chords: ['Em', 'C', 'G', 'D', 'Am', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 3,
    difficulty: 'easy',
    tags: ['定番', '弾き語り', '結婚式'],
  },
  {
    id: 'song_059',
    title: 'First Love',
    artist: '宇多田ヒカル',
    year: 1999,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['Am', 'Dm', 'G', 'C'] },
      { label: 'Aメロ', chords: ['Am', 'Dm', 'G', 'C', 'Em', 'F', 'G'] },
      { label: 'サビ', chords: ['F', 'G', 'C', 'Am', 'Dm', 'G', 'C'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', '90s'],
  },
  {
    id: 'song_060',
    title: 'いつかのメリークリスマス',
    artist: 'B\'z',
    year: 1992,
    decade: '90s',
    genre: 'rock',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['クリスマス', '定番', '弾き語り'],
  },
  {
    id: 'song_061',
    title: 'それが大事',
    artist: '大事MANブラザーズバンド',
    year: 1991,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'Am'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'D', 'G'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '応援歌'],
  },
  {
    id: 'song_062',
    title: '世界中の誰よりきっと',
    artist: '中山美穂 & WANDS',
    year: 1992,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Am', 'C', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_063',
    title: 'PRIDE',
    artist: '今井美樹',
    year: 1996,
    decade: '90s',
    genre: 'jpop',
    youtubeId: 'dQw4w9WgXcQ',
    sections: [
      { label: 'イントロ', chords: ['G', 'D', 'Em', 'C'] },
      { label: 'Aメロ', chords: ['G', 'D', 'Em', 'Bm', 'Am', 'D'] },
      { label: 'サビ', chords: ['C', 'D', 'G', 'Em', 'Am', 'Bm', 'C', 'D'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['バラード', '定番'],
  },
]
