import { Song } from '@/types'

export const songs80s: Song[] = [
  {
    id: 'song_001',
    title: 'I LOVE YOU',
    artist: '尾崎豊',
    year: 1983,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'EsOsc-sajMk',
    sections: [
      { label: 'イントロ', chords: ['G', 'Bm7', 'Em7', 'Am7'] },
      { label: 'Aメロ', chords: ['G', 'Bm7', 'Em7', 'Am7', 'D7'] },
      { label: 'Bメロ', chords: ['C', 'D7', 'Em7'] },
      { label: 'サビ', chords: ['Em7', 'Am7', 'D7', 'G'] },
      { label: '間奏', chords: ['Am7/D', 'G', 'Bm7'] },
      { label: 'アウトロ', chords: ['Em7', 'Am7', 'D7', 'G'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_002',
    title: 'MARIONETTE',
    artist: 'BOØWY',
    year: 1985,
    decade: '80s',
    genre: 'rock',
    youtubeId: 'UQ5BLs-2C5A',
    sections: [
      { label: 'イントロ', chords: ['Em', 'Am', 'D', 'G'] },
      { label: 'Aメロ', chords: ['Em', 'B7', 'C', 'G'] },
      { label: 'Bメロ', chords: ['D', 'Am', 'C', 'D'] },
      { label: 'サビ', chords: ['Em', 'B7', 'C', 'G', 'D', 'Am', 'C', 'D'] },
      { label: '間奏', chords: ['Em', 'Am', 'D', 'G'] },
      { label: 'ブリッジ', chords: ['C', 'G', 'D', 'Em7'] },
      { label: 'アウトロ', chords: ['Em', 'Am', 'D', 'G'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['ロック', '定番'],
  },
  {
    id: 'song_003',
    title: '真夏の果実',
    artist: 'サザンオールスターズ',
    year: 1990,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'or0uXpwT-P8',
    sections: [
      { label: 'イントロ', chords: ['D', 'A', 'Bm7', 'F#m7', 'Gadd9', 'D', 'Em7', 'A7'] },
      { label: 'Aメロ', chords: ['D', 'A', 'Bm7', 'F#m7', 'Gadd9', 'D', 'Em7', 'A7'] },
      { label: 'Bメロ', chords: ['G', 'D', 'C', 'Em7'] },
      { label: 'サビ', chords: ['D', 'A', 'Bm7', 'F#m7', 'Gadd9', 'D', 'Em7', 'A7'] },
      { label: '間奏', chords: ['Em7', 'Gm', 'A7', 'D'] },
      { label: 'ブリッジ', chords: ['Gmaj7', 'F#7', 'Bm7', 'Em7', 'Gm7', 'A7'] },
      { label: 'アウトロ', chords: ['D', 'A', 'Bm7', 'F#m7', 'Gadd9', 'D', 'Em7', 'A7'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['夏', '定番', '弾き語り'],
  },
  {
    id: 'song_010',
    title: '卒業',
    artist: '尾崎豊',
    year: 1985,
    decade: '80s',
    genre: 'rock',
    youtubeId: 'HUHUsfbvw9I',
    sections: [
      { label: 'イントロ', chords: ['B', 'D', 'C', 'C/D', 'G', 'D', 'C', 'C/D'] },
      { label: 'Aメロ', chords: ['G', 'D', 'C', 'Am7', 'D7sus4'] },
      { label: 'Bメロ', chords: ['C', 'G', 'Am7', 'D7sus4'] },
      { label: 'サビ', chords: ['G', 'D', 'C', 'Em7', 'Am7', 'G6', 'D', 'C', 'Em7'] },
      { label: '間奏', chords: ['G', 'D', 'C', 'C/D'] },
      { label: 'アウトロ', chords: ['G', 'D', 'C', 'Em7'] },
    ],
    capo: 2,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', '青春'],
  },
  {
    id: 'song_011',
    title: '15の夜',
    artist: '尾崎豊',
    year: 1983,
    decade: '80s',
    genre: 'rock',
    youtubeId: 'rBbEv6OFnVE',
    sections: [
      { label: 'イントロ', chords: ['C', 'E7', 'Am', 'Am7'] },
      { label: 'Aメロ', chords: ['C', 'E7', 'Am', 'Am7', 'F', 'G', 'Em7', 'Cmaj7'] },
      { label: 'Bメロ', chords: ['C', 'D', 'G', 'D', 'Em7'] },
      { label: 'サビ', chords: ['Am7', 'G6', 'D', 'Em7', 'Dm7', 'G'] },
      { label: '間奏', chords: ['C', 'E7', 'F', 'G'] },
      { label: 'ブリッジ', chords: ['Fmaj7', 'Cmaj7', 'Dm7', 'G'] },
      { label: 'アウトロ', chords: ['C', 'G', 'C', 'G', 'C'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', '青春'],
  },
  {
    id: 'song_012',
    title: '乾杯',
    artist: '長渕剛',
    year: 1980,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'TjkYUnnswrk',
    sections: [
      { label: 'イントロ', chords: ['D', 'D7', 'G', 'Gdim', 'A', 'D', 'Gm'] },
      { label: 'Aメロ', chords: ['D', 'D7', 'G', 'D', 'A7'] },
      { label: 'サビ', chords: ['D', 'D7', 'G', 'Gdim', 'A', 'D', 'Gm'] },
      { label: '間奏', chords: ['D', 'D7', 'G', 'D', 'A7'] },
      { label: 'アウトロ', chords: ['D', 'D7', 'G', 'D', 'A7'] },
    ],
    capo: 2,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', '宴会'],
  },
  {
    id: 'song_013',
    title: 'さよなら',
    artist: 'オフコース',
    year: 1982,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'l-xcmbvi-YY',
    sections: [
      { label: 'イントロ', chords: ['C', 'Em', 'C', 'Em7'] },
      { label: 'Aメロ', chords: ['C', 'Em', 'Bm', 'Em'] },
      { label: 'Bメロ', chords: ['C', 'Em', 'Bm', 'Em'] },
      { label: 'サビ', chords: ['C', 'G', 'D', 'Em', 'D', 'C', 'D'] },
      { label: '間奏', chords: ['Em', 'Bm', 'Em', 'Bm'] },
      { label: 'アウトロ', chords: ['C', 'Em', 'C', 'Em'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['バラード', '定番', '弾き語り'],
  },
  {
    id: 'song_014',
    title: 'SOMEDAY',
    artist: '佐野元春',
    year: 1982,
    decade: '80s',
    genre: 'rock',
    youtubeId: 'n7XYTaKVcSg',
    sections: [
      { label: 'イントロ', chords: ['C', 'Am', 'Dm', 'G', 'C', 'Am', 'Dm', 'G', 'C'] },
      { label: 'Aメロ', chords: ['C', 'Em', 'F', 'Esus4', 'E'] },
      { label: 'Bメロ', chords: ['Am', 'Dm', 'G'] },
      { label: 'サビ', chords: ['Am', 'Dm', 'G', 'C', 'Cadd9', 'Csus4'] },
      { label: '間奏', chords: ['F', 'Gsus4', 'G', 'Gsus4', 'G', 'Gsus4', 'G'] },
      { label: 'アウトロ', chords: ['C', 'Am7', 'Em7', 'Am7', 'Em', 'Em7', 'Am7'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['定番', '80s', '弾き語り'],
  },
  {
    id: 'song_015',
    title: '涙のリクエスト',
    artist: 'チェッカーズ',
    year: 1984,
    decade: '80s',
    genre: 'pops',
    youtubeId: 'N7MHXbsT3J4',
    sections: [
      { label: 'イントロ', chords: ['A', 'Bm', 'Em', 'Bm', 'Em'] },
      { label: 'Aメロ', chords: ['A', 'G/E', 'A', 'G/E'] },
      { label: 'Bメロ', chords: ['Bm', 'A', 'G/E', 'A', 'G/E'] },
      { label: 'サビ', chords: ['Bb', 'C#', 'D', 'Bb', 'C#'] },
      { label: '間奏', chords: ['Em', 'Bm', 'Em', 'Bm'] },
      { label: 'アウトロ', chords: ['A', 'G/E', 'A'] },
    ],
    capo: 1,
    difficulty: 'hard',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_016',
    title: 'ワインレッドの心',
    artist: '安全地帯',
    year: 1983,
    decade: '80s',
    genre: 'jpop',
    youtubeId: '7h5BxzNSM9w',
    sections: [
      { label: 'イントロ', chords: ['Em', 'Cmaj7', 'Em', 'Cmaj7'] },
      { label: 'Aメロ', chords: ['Em', 'Cmaj7', 'Em', 'Dm7', 'Em7', 'Cmaj7'] },
      { label: 'Bメロ', chords: ['Em', 'Dm7', 'Cmaj7', 'Bm7', 'Cmaj7'] },
      { label: 'サビ', chords: ['Am7', 'B7sus4', 'B7', 'Em7', 'Am7'] },
      { label: '間奏', chords: ['Em', 'Em7', 'Am7', 'B7'] },
      { label: 'アウトロ', chords: ['Cmaj7', 'B7', 'Em', 'B7', 'Em'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['バラード', '定番', '弾き語り'],
  },
  {
    id: 'song_017',
    title: '恋の予感',
    artist: '安全地帯',
    year: 1985,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'GO7gR-NJu7o',
    sections: [
      { label: 'イントロ', chords: ['Fmaj7', 'G6', 'Gadd9', 'Fmaj7', 'Dm7', 'Bm7b5', 'Esus4', 'E'] },
      { label: 'Aメロ', chords: ['Fmaj7', 'F6', 'Em7', 'Am', 'Am/G'] },
      { label: 'Bメロ', chords: ['Fmaj7', 'G/F', 'Em7', 'E7'] },
      { label: 'サビ', chords: ['Fmaj7', 'Gadd9', 'Am', 'Fmaj7', 'Gadd9', 'Am'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['バラード', '定番'],
  },
  {
    id: 'song_018',
    title: 'Get Wild',
    artist: 'TM NETWORK',
    year: 1987,
    decade: '80s',
    genre: 'pops',
    youtubeId: 'r107W1YXrSM',
    sections: [
      { label: 'イントロ', chords: ['F#m', 'E', 'F#', 'B'] },
      { label: 'Aメロ', chords: ['Bm', 'F#m', 'G', 'A'] },
      { label: 'Bメロ', chords: ['Bm', 'F#m', 'G', 'A', 'Bm', 'D', 'E'] },
      { label: 'サビ', chords: ['G', 'C#m', 'E', 'F#'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['定番', '80s'],
  },
  {
    id: 'song_019',
    title: 'J.BOY',
    artist: '浜田省吾',
    year: 1986,
    decade: '80s',
    genre: 'rock',
    youtubeId: 'xrUvoKQL2JQ',
    sections: [
      { label: 'イントロ', chords: ['C', 'D', 'Bm', 'Em'] },
      { label: 'Aメロ', chords: ['C', 'D', 'Bm', 'Em'] },
      { label: 'Bメロ', chords: ['C', 'D', 'Em'] },
      { label: 'サビ', chords: ['C', 'D', 'Bm', 'Em', 'C', 'D', 'Em'] },
    ],
    capo: 5,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', 'ロック'],
  },
  {
    id: 'song_020',
    title: '悲しみは雪のように',
    artist: '浜田省吾',
    year: 1992,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'Oy7fhdAWvpk',
    sections: [
      { label: 'イントロ', chords: ['G', 'Em7', 'G', 'Em7'] },
      { label: 'Aメロ', chords: ['G', 'Em7', 'Am7', 'C', 'Am7/D'] },
      { label: 'Bメロ', chords: ['G', 'Em7', 'Am7', 'C', 'Am7/D', 'G', 'D'] },
      { label: 'サビ', chords: ['G', 'Em7', 'Am7', 'D'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['バラード', '弾き語り', '冬'],
  },
  {
    id: 'song_021',
    title: 'DREAMIN\'',
    artist: 'BOØWY',
    year: 1986,
    decade: '80s',
    genre: 'rock',
    youtubeId: '3AH5UyLZUtQ',
    sections: [
      { label: 'イントロ', chords: ['C', 'F', 'G'] },
      { label: 'Aメロ', chords: ['C', 'F', 'G', 'Em', 'Am', 'G', 'F', 'G'] },
      { label: 'Bメロ', chords: ['Dm', 'Am'] },
      { label: 'サビ', chords: ['C', 'G', 'E7', 'Am', 'G', 'F', 'G'] },
      { label: 'アウトロ', chords: ['C', 'F', 'G'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['ロック', '定番'],
  },
  {
    id: 'song_022',
    title: '駅',
    artist: '竹内まりや',
    year: 1987,
    decade: '80s',
    genre: 'jpop',
    youtubeId: '2JBVwMIPXO8',
    sections: [
      { label: 'イントロ', chords: ['Am7', 'B7', 'Em7'] },
      { label: 'Aメロ', chords: ['Am7', 'B7', 'Em7', 'Dm7/G', 'Cmaj7', 'Fmaj7'] },
      { label: 'Bメロ', chords: ['Cmaj7', 'Bm7', 'Am7', 'C/D'] },
      { label: 'サビ', chords: ['Em7', 'D6', 'Cmaj7', 'Fmaj7'] },
      { label: 'アウトロ', chords: ['Em7', 'D6'] },
    ],
    capo: 2,
    difficulty: 'hard',
    tags: ['バラード', '定番', '弾き語り'],
  },
  {
    id: 'song_023',
    title: 'ギザギザハートの子守唄',
    artist: 'チェッカーズ',
    year: 1983,
    decade: '80s',
    genre: 'pops',
    youtubeId: 'dvbjQoX9p6o',
    sections: [
      { label: 'イントロ', chords: ['Em', 'Am', 'B7'] },
      { label: 'Aメロ', chords: ['Em', 'Am', 'B7', 'Em'] },
      { label: 'サビ', chords: ['Am', 'D', 'B7', 'Em'] },
      { label: '間奏', chords: ['Em', 'Am', 'B7'] },
      { label: 'ブリッジ', chords: ['Am', 'Em', 'B7', 'Em'] },
      { label: 'アウトロ', chords: ['Em'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['定番', '80s'],
  },
  {
    id: 'song_024',
    title: '雨上がりの夜空に',
    artist: 'RCサクセション',
    year: 1980,
    decade: '80s',
    genre: 'rock',
    youtubeId: '4CZZslbCWaQ',
    sections: [
      { label: 'イントロ', chords: ['D', 'Dsus4', 'D'] },
      { label: 'Aメロ', chords: ['D', 'Dsus4', 'D', 'A', 'G', 'D'] },
      { label: 'サビ', chords: ['A', 'G', 'D', 'A'] },
      { label: 'ブリッジ', chords: ['A', 'G', 'D'] },
      { label: 'アウトロ', chords: ['A', 'G', 'D'] },
    ],
    capo: 0,
    difficulty: 'easy',
    tags: ['ロック', '定番'],
  },
  {
    id: 'song_025',
    title: 'クリスマス・イブ',
    artist: '山下達郎',
    year: 1983,
    decade: '80s',
    genre: 'jpop',
    youtubeId: '1-xwxyHOyVw',
    sections: [
      { label: 'イントロ', chords: ['Cmaj7', 'Bm7', 'Am7', 'C/D'] },
      { label: 'Aメロ', chords: ['D', 'Cmaj7', 'Bm7', 'Am7', 'C/D'] },
      { label: 'サビ', chords: ['Cmaj7', 'Bm7', 'Am7', 'C/D', 'Cmaj7', 'Bm7', 'Em7', 'D6'] },
      { label: 'ブリッジ', chords: ['Em7', 'D6', 'Cmaj7', 'Bm7'] },
      { label: 'アウトロ', chords: ['Cmaj7', 'Bm7', 'Am7', 'C/D'] },
    ],
    capo: 2,
    difficulty: 'hard',
    tags: ['クリスマス', '定番', '弾き語り'],
  },
  {
    id: 'song_026',
    title: '少女A',
    artist: '中森明菜',
    year: 1982,
    decade: '80s',
    genre: 'pops',
    youtubeId: 'pNNn0izjwDI',
    sections: [
      { label: 'イントロ', chords: ['C', 'B', 'Em', 'Dm', 'G'] },
      { label: 'Aメロ', chords: ['C', 'B', 'Em', 'Dm', 'G'] },
      { label: 'Bメロ', chords: ['Dm', 'G', 'C'] },
      { label: 'サビ', chords: ['Em', 'Dm', 'G', 'C'] },
      { label: 'ブリッジ', chords: ['C', 'B', 'Em', 'Dm', 'G'] },
      { label: 'アウトロ', chords: ['Em'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '80s'],
  },
  {
    id: 'song_027',
    title: 'Forget-me-not',
    artist: '尾崎豊',
    year: 1986,
    decade: '80s',
    genre: 'rock',
    youtubeId: 'djA_CP5DYJQ',
    sections: [
      { label: 'イントロ', chords: ['Dadd9', 'A/B', 'Bm7', 'G'] },
      { label: 'Aメロ', chords: ['Dadd9', 'A/B', 'Bm7', 'G', 'Gm', 'A7'] },
      { label: 'Bメロ', chords: ['Bm7', 'F#m7', 'G', 'A7', 'D'] },
      { label: 'サビ', chords: ['Bm7', 'F#m7', 'G', 'A7', 'D', 'A', 'Bm', 'A', 'G', 'G/A', 'A7', 'D', 'G/A', 'A7'] },
      { label: '間奏', chords: ['D', 'A', 'Bm', 'A', 'G', 'G/A', 'Bm7', 'D7', 'Bm', 'Gm'] },
      { label: 'アウトロ', chords: ['D7', 'G', 'Gm'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['弾き語り', '青春', '尾崎豊'],
  },
  {
    id: 'song_028',
    title: '恋',
    artist: '松山千春',
    year: 1980,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'q7rexuB2KKI',
    sections: [
      { label: 'イントロ', chords: ['G', 'Bm7', 'Am7', 'D7'] },
      { label: 'Aメロ', chords: ['G', 'Bm7', 'Am7', 'D7', 'G', 'G7'] },
      { label: 'Bメロ', chords: ['C', 'G', 'Bm', 'Em', 'Am7', 'D7'] },
      { label: 'サビ', chords: ['G', 'Bm7', 'Am7', 'D7', 'G', 'G7', 'C', 'Bm7', 'Am7', 'D7'] },
      { label: '間奏', chords: ['G', 'Am7', 'D7', 'G', 'G7'] },
      { label: 'アウトロ', chords: ['C', 'G', 'Am7', 'D7', 'G'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り', 'フォーク'],
  },
  {
    id: 'song_029',
    title: 'ルビーの指環',
    artist: '寺尾聡',
    year: 1981,
    decade: '80s',
    genre: 'jpop',
    youtubeId: '3ii96gUvUlM',
    sections: [
      { label: 'イントロ', chords: ['Em', 'G#dim', 'Fmaj7', 'B7', 'Em', 'Em7'] },
      { label: 'Aメロ', chords: ['Em', 'E', 'Am7', 'D7', 'G', 'Em', 'Am', 'D'] },
      { label: 'Bメロ', chords: ['C', 'Em', 'Am', 'D7', 'G', 'Fmaj7', 'C7', 'Fm'] },
      { label: 'サビ', chords: ['Em', 'Em7', 'B7', 'Em', 'Em7', 'B', 'Em', 'E', 'Am7', 'Dm7', 'G', 'Gm7', 'C7', 'Fm', 'A#m7'] },
      { label: '間奏', chords: ['Em', 'Em7', 'B7', 'Em7'] },
      { label: 'アウトロ', chords: ['C7', 'Fm', 'C7'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['バラード', '定番'],
  },
  {
    id: 'song_030',
    title: 'もしもピアノが弾けたなら',
    artist: '西田敏行',
    year: 1981,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'RkyVwvaSTyE',
    sections: [
      { label: 'イントロ', chords: ['C', 'Dm', 'G', 'C'] },
      { label: 'Aメロ', chords: ['C', 'Em', 'Am', 'Em', 'C', 'F', 'G', 'C'] },
      { label: 'Bメロ', chords: ['Dm', 'G', 'C', 'Em', 'Am', 'Em'] },
      { label: 'サビ', chords: ['C', 'F', 'G', 'C', 'Dm', 'G', 'C', 'C', 'F', 'G', 'C'] },
      { label: '間奏', chords: ['Am', 'Em', 'F', 'Fdim', 'C', 'A', 'D', 'G'] },
      { label: 'アウトロ', chords: ['Am', 'Em', 'Dm', 'G', 'C'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_031',
    title: '北の国から',
    artist: 'さだまさし',
    year: 1981,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'xCjzkgLcfDs',
    sections: [
      { label: 'イントロ', chords: ['G'] },
      { label: 'Aメロ', chords: ['G', 'Am7', 'D7', 'G', 'G7', 'C', 'G', 'D7', 'G'] },
      { label: 'Bメロ', chords: ['C', 'G', 'D7sus4', 'D7', 'G', 'G7', 'C', 'Bm7', 'Am7', 'D7'] },
      { label: 'サビ', chords: ['G', 'Am7', 'D7', 'G', 'G7', 'C', 'G', 'D7', 'G', 'G7'] },
      { label: '間奏', chords: ['C', 'G', 'D7sus4', 'D7', 'G', 'G7', 'C', 'G', 'D7', 'G'] },
      { label: 'アウトロ', chords: ['G', 'Am7', 'D7', 'G', 'F#', 'Am7', 'D7', 'G'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['定番', '弾き語り'],
  },
  {
    id: 'song_032',
    title: '夏の終わりのハーモニー',
    artist: '井上陽水 & 安全地帯',
    year: 1986,
    decade: '80s',
    genre: 'jpop',
    youtubeId: 'WCSeiSOaHxY',
    sections: [
      { label: 'イントロ', chords: ['D', 'G', 'Fmaj7', 'Em7', 'A7'] },
      { label: 'Aメロ', chords: ['D', 'Dmaj7', 'G', 'Gm'] },
      { label: 'Bメロ', chords: ['D', 'Dmaj7', 'G', 'A7'] },
      { label: 'サビ', chords: ['Fmaj7', 'Em7', 'A', 'A7'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['バラード', '夏', '定番', 'デュエット'],
  },
  {
    id: 'song_033',
    title: 'セーラー服と機関銃',
    artist: '薬師丸ひろ子',
    year: 1981,
    decade: '80s',
    genre: 'pops',
    youtubeId: '9H4vJUZhsgw',
    sections: [
      { label: 'イントロ', chords: ['Dm', 'C', 'Bbmaj7', 'Am7'] },
      { label: 'Aメロ', chords: ['Dm', 'C', 'Bbmaj7', 'Am7'] },
      { label: 'Bメロ', chords: ['Gm7', 'Dm/F'] },
      { label: 'サビ', chords: ['Em7b5', 'A7', 'Dm'] },
      { label: 'アウトロ', chords: ['Dm', 'C', 'Bbmaj7', 'Am7'] },
    ],
    capo: 5,
    difficulty: 'hard',
    tags: ['定番', '80s'],
  },
  {
    id: 'song_034',
    title: 'SELF CONTROL',
    artist: 'TM NETWORK',
    year: 1987,
    decade: '80s',
    genre: 'pops',
    youtubeId: '55onTCwpm2g',
    sections: [
      { label: 'イントロ', chords: ['D', 'A', 'G'] },
      { label: 'Aメロ', chords: ['D', 'A', 'G', 'F#m', 'Bm', 'A', 'D', 'E'] },
      { label: 'Bメロ', chords: ['F#m', 'Bm', 'A', 'D'] },
      { label: 'サビ', chords: ['D', 'A', 'G', 'A7sus4'] },
    ],
    capo: 0,
    difficulty: 'medium',
    tags: ['80s'],
  },
  {
    id: 'song_035',
    title: '時間よ止まれ',
    artist: '矢沢永吉',
    year: 1978,
    decade: '80s',
    genre: 'rock',
    youtubeId: 'B-auiB7AJY4',
    sections: [
      { label: 'イントロ', chords: ['C', 'Am7', 'Fm', 'G'] },
      { label: 'Aメロ', chords: ['C', 'Caug', 'Em7', 'G7'] },
      { label: 'Bメロ', chords: ['Am', 'Dm7', 'F/G'] },
      { label: 'サビ', chords: ['Dm7', 'G7', 'Em7', 'A7', 'Dm'] },
    ],
    capo: 0,
    difficulty: 'hard',
    tags: ['定番', '弾き語り'],
  },
]
